### ISSUE TITLE
npm run commit

### ISSUE THREAD

**Issue by goliney** [BenoitAverty/generator-javascript-library#1]
I wonder, why to run `./node_modules/.bin/git-cz`, whereas you can have a script in package.json, like [I do here](https://github.com/goliney/coderoom/blob/master/package.json#L43). `npm run commit` looks prettier, imho.

**Comment by BenoitAverty** [comment]
The reason I didn't put a script in package.json is because I find it to be unnecessary, and there is already quite a lot of scripts. I usually just run git cz (by installing commitizen globally). In the setup instructions I decided to put that here and suggest the global commitizen install a little bit later (in the "other useful things" section).

I agree that it's a bit ugly. Maybe I should add the commitizen install before this section in the readme, would that be better?
